name: fnothing — Global Scanner PRO

on:
  schedule:
    - cron: "*/30 * * * *"   # alle 30 Minuten
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run scanner
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ONESIGNAL_REST_KEY: ${{ secrets.ONESIGNAL_REST_KEY }}
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
          SCORE_THRESHOLD: "72"        # kannst du anpassen
          QUIET_TZ: "Europe/Berlin"
          QUIET_START: "23"
          QUIET_END: "6"
          DEDUPE_HOURS: "6"
          CONCURRENCY: "4"
          MAX_HEADLINES: "4"
        run: node scanner.mjs

      - name: Commit reports & dedupe state
        run: |
          git config user.name "fnothing-bot"
          git config user.email "bot@users.noreply.github.com"
          git add reports/*.json state.json || true
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "scanner: update report/state $(date -u +%FT%TZ)" || true
            git push
          fi
