name: fnothing — Global Scanner PRO

on:
  schedule:
    - cron: "*/30 * * * *"   # alle 30 Minuten
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Optionaler Debug-Step – zeigt nur, ob die Env vorhanden ist (true/false)
      - name: Check env presence
        run: |
          node -e "console.log({
            OPENAI: !!process.env.OPENAI_API_KEY,
            ONE_APP: !!process.env.ONESIGNAL_APP_ID,
            ONE_REST: !!process.env.ONESIGNAL_REST_KEY
          })"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || vars.OPENAI_API_KEY }}
          ONESIGNAL_REST_KEY: ${{ secrets.ONESIGNAL_REST_KEY || vars.ONESIGNAL_REST_KEY }}
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID || vars.ONESIGNAL_APP_ID }}

      - name: Run scanner
        env:
          # Nimmt Secrets, fällt sonst auf Variables zurück
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || vars.OPENAI_API_KEY }}
          ONESIGNAL_REST_KEY: ${{ secrets.ONESIGNAL_REST_KEY || vars.ONESIGNAL_REST_KEY }}
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID || vars.ONESIGNAL_APP_ID }}

          # Feintuning (kannst du ändern)
          SCORE_THRESHOLD: "72"
          QUIET_TZ: "Europe/Berlin"
          QUIET_START: "23"
          QUIET_END: "6"
          DEDUPE_HOURS: "6"
          CONCURRENCY: "4"
          MAX_HEADLINES: "4"
        run: node scanner.mjs

      - name: Commit reports & dedupe state
        run: |
          git config user.name "fnothing-bot"
          git config user.email "bot@users.noreply.github.com"
          git add reports/*.json state.json || true
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "scanner: update report/state $(date -u +%FT%TZ)" || true
            git push
          fi
